exports.taskListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
                <div class="w3-container w3-teal">
                    <h1>Input task</h1>
                </div>
            
                <form class="w3-container" method="post">
                    <label class="w3-text-teal"><b>Nome</b></label>
                    <input class="w3-input w3-border w3-light-grey" name="nome"type="text" value=""/>
                
                    <label class="w3-text-teal"><b>Task Description</b></label>
                    <input class="w3-input w3-border w3-light-grey" name="TaskDescription" type="text" value=""/>
                    
                    <label class="w3-text-teal"><b>Choose the date limit to do the task</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="date" name="DateTask" min="`+d.split("T")[0]+`" value=""/>
                    
                    
                    <button class="w3-btn w3-blue w3-mb-2" name="Done" value="0" type="submit">Submit</button>
                    <p/>
                </form>

                <header class="w3-container w3-teal">
                        <h3>Task List</h3>   
                </header>

                <div class="w3-row">
                    <div class="w3-col w3-container m6 l6">
                        <h4>Tasks to Do:</h4>
                            <table class="w3-table-all">
                                <tr>
                                    <th>Nome</th><th>Task Description</th><th>DateTask</th>
                                </tr>
                `
    for(let i=0; i < slist.length ; i++){
        if(slist[i]["Done"]==0){
            pagHTML += `
                <tr>
                    <td>${slist[i].nome}</td>
                    <td>${slist[i].TaskDescription}</td>
                    <td>${slist[i].DateTask}</td>
                    <td>
                        <a href="/tasks/Done/${slist[i].id}" class="button w3-btn w3-blue w3-mb-2" type="submit">Done</a>
                        <a href="/tasks/Edit/${slist[i].id}" class="button w3-btn w3-blue w3-mb-2" type="submit">Edit</a>
                        <a href="/tasks/Delete/${slist[i].id}" class="button w3-btn w3-blue w3-mb-2" type="submit">Delete</a>
                    </td>
                </tr>
        `
        }
    }
    pagHTML+=`
                        </table>
                        <p/>
                </div>
            <div class="w3-col w3-container m6 l6"> 
                <h4>Tasks Done:</h4>
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th><th>Task Description</th><th>DateTask</th>
                        </tr>
    `
    for(let i=0; i < slist.length ; i++){
        if(slist[i]["Done"]==1){
            pagHTML += `
            <tr>
                <td>${slist[i].nome}</td>
                <td>${slist[i].TaskDescription}</td>
                <td>${slist[i].DateTask}</td>
                <td>
                    <a href="/tasks/Edit/${slist[i].id}" class="button w3-btn w3-blue w3-mb-2" type="submit">Edit</a>
                    <a href="/tasks/Delete/${slist[i].id}" class="button w3-btn w3-blue w3-mb-2" type="submit">Delete</a>
                </td>
            </tr>
    `
        }
    }

    pagHTML += `
                    </table>
                </div>
            </div>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.tasksEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>TaskDescription</label>
                        <input class="w3-input w3-round" type="text" name="TaskDescription" value="${a.TaskDescription}"/>
                        <label>DateTask</label>
                        <input class="w3-input w3-round" type="text" name="DateTask" value="${a.DateTask}"/>
                        <label>Done(1-Verdadeiro,0-falso)</label>
                        <input class="w3-input w3-round" type="text" name="Done" value="${a.Done}"/>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Edit</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.confirmPage = function( func,task, d ){
    return `
    <p>${d}: Function ${func}: ${task}.</p>
    <a href="http://localhost:7777/tasks">Done</a>
    `
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}